// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaContaUsuario.Models;

#nullable disable

namespace SistemaContaUsuario.Migrations
{
    [DbContext(typeof(ContaUsuarioContext))]
    partial class ContaUsuarioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SistemaContaUsuario.Models.ContaUsuario", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("titular")
                        .HasColumnType("longtext");

                    b.Property<int>("agencia")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("numero")
                        .HasColumnType("longtext");

                    b.Property<double>("saldo")
                        .HasColumnType("double");

                    b.Property<string>("tipoConta")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("ContasUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
